orange:
  outputs:

    dev:
      type: postgres
      threads: 1
      host: 172.19.0.3
      port: 5432
      user: postgres
      pass: password
      dbname: postgres
      schema: postgres

  target: dev
